### ISSUE TITLE
3.1.1 gradle issue

### ISSUE THREAD

**Issue by chauhan9909** [web3j/sample-project-gradle#1]
![untitled](https://user-images.githubusercontent.com/7007376/33126696-68a47bc2-cfab-11e7-862e-b0b7becf9bae.png)

**Comment by conor10** [comment]
Please try using 3.1.1-android.

**Comment by vingorius** [comment]
After using 3.1.1-android, error occured as below when building time.

Error:(24, 32) error: cannot find symbol method build(HttpService)

![image](https://user-images.githubusercontent.com/5274928/33803210-85deb4ac-ddcd-11e7-96bb-fa83da8a5313.png)

**Comment by Abasifreke** [comment]
I got the same issue as above. I have been trying to build this sample project as an Android project for a while now. But I keep getting gradle issues. @conor10 is there any way you could please try compiling as an Android project and giving us an android version of this project? Thank you.

**Comment by vingorius** [comment]
Thanks @Abasifreke , you save my times.

**Comment by conor10** [comment]
I've added a comment to help Android users, see https://github.com/web3j/sample-project-gradle/blob/master/src/main/java/org/web3j/sample/Application.java#L57.
