### ISSUE TITLE
can't import org.web3j.sample.contracts.generated.Greeter

### ISSUE THREAD

**Issue by JohannesKreuz** [web3j/sample-project-gradle#12]
Hi,

I loaded this project in eclipse to run. But eclipse didn`t find all libaries.
Could you Show me where I can find this libary?

"org.web3j.sample.contracts.generated.Greeter"

Thanks for your help.

**Comment by NetkoNefarious** [comment]
I have the same problem and unfortunately; there aren't any wrapper classes for the contract so you'll have to compile it yourself. You must download the appropriate version of Solidity compiler (look for the version in the sol file, at the time of writing it's [0.4.25](https://github.com/ethereum/solidity/releases/tag/v0.4.25)) and web3j CLI ([latest version, zip](https://github.com/web3j/web3j/releases/tag/v4.1.1)). Follow [this guide](https://web3j.readthedocs.io/en/latest/getting_started.html#working-with-smart-contracts-with-java-smart-contract-wrappers) to generate the wrapper code.

**Comment by iikirilov** [comment]
This project uses the web3j-gradle-plugin which will generate the smart-contract wrapper for you.

Not 100% sure but it should also download solidity if you don't have. But I may be wrong here.

You can use `./gradlew tasks` to list the gradle tasks. It should be obvious what to do.

`./gradlew build` will also generate your smart-contract wrapper.
